### ISSUE TITLE
Вопрос по архитектуре

### ISSUE THREAD

**Issue by lalaka32** [kuzmenkovdmitrii/Training#1]
Привет, у тебя интересная структура проекта. Ты где-то нашёл пример, или всё сам придумал? Если первое то можешь поделиться источником?)

**Comment by lalaka32** [comment]
Я имею ввиду последний проект.

**Comment by kuzmenkovdmitrii** [comment]
тут вообще зачем это нужно [https://metanit.com/sharp/mvc5/23.1.php](url)

а тут уже примеры [https://metanit.com/sharp/mvc5/23.7.php](url)

финальный проект будет +- таким 
![image](https://user-images.githubusercontent.com/36965381/48677804-6ad31500-eb8b-11e8-90cc-5ee9ac68eea3.png)
